### ISSUE TITLE
Does not work with 3.2-RC1 

### ISSUE THREAD

**Issue by tristanryerparke** [Sindarius/DWC_GamepadJogger_Plugin#1]
Are you planning to update this plugin? DWC says the firmware version is wrong when trying to install. Would love to give this a try, thanks.

**Comment by Sindarius** [comment]
I do plan on updating this soon with a few changes. However, in the short term you can pop open the zip file, open the plugin.json file and change the version number to 3.2 and it should work just fine.

**Comment by Sindarius** [comment]
New version up with the change
https://github.com/Sindarius/DWC_GamepadJogger_Plugin/releases/tag/0.1.2

**Comment by tristanryerparke** [comment]
Just gave the new version a try, getting this error:
![Screen Shot 2020-12-21 at 5 32 05 PM](https://user-images.githubusercontent.com/57774376/102828393-9bad5600-43b2-11eb-9797-0bc37de0e368.png)

**Comment by Sindarius** [comment]
I'll pull down the latest RC and take a look. I tend to have my own versions floating around.

**Comment by Sindarius** [comment]
Can you verify that DWC-rc1 is running in settings > general
![image](https://user-images.githubusercontent.com/12520045/102828906-749f5600-43ab-11eb-920d-8257fcf25dc0.png)

**Comment by tristanryerparke** [comment]
Yup:
![Screen Shot 2020-12-21 at 5 43 15 PM](https://user-images.githubusercontent.com/57774376/102829028-217dd100-43b4-11eb-89fc-b7fcaee4795e.png)
![Screen Shot 2020-12-21 at 5 43 25 PM](https://user-images.githubusercontent.com/57774376/102829031-2478c180-43b4-11eb-9c5c-31ad495e3a62.png)
running on a pi4

**Comment by Sindarius** [comment]
I see that plugins were disabled on the SBC in the DSF code. Not sure why at the moment.

**Comment by Sindarius** [comment]
Looks like this should be resolved in RC-2 for web plugins.

**Comment by scrhall** [comment]
Is working on https://github.com/Duet3D/DWC-CNC , changing the version on the json

**Comment by Sindarius** [comment]
> Is working on https://github.com/Duet3D/DWC-CNC , changing the version on the json

The plugin will work fine on standalone duets but it will not install on a SBC due to changes in the DSF that disabled installing plugins. I have been told this will be addressed in 3.2 RC-2 for web only plugins like this one.
