### ISSUE TITLE
Not working with RepRapFirmware 3.3

### ISSUE THREAD

**Issue by oforiandy** [Sindarius/DWC_GamepadJogger_Plugin#2]
Are there any plans to update this plugin so it works with the latest firmware?

**Comment by Sindarius** [comment]
I can update the release. A simple fix is open the zip file and update the plugin.json and change it from 3.3 to 3.4

**Comment by Sindarius** [comment]
Nevermind, it looks like it has to be rebuilt due to plugin structure changes. I'll get a new build out shortly

**Comment by Sindarius** [comment]
Here are updated versions of the plugin for 3.3 and 3.4
https://github.com/Sindarius/DWC_GamepadJogger_Plugin/releases/tag/1.0.0

**Comment by oforiandy** [comment]
Thanks a lot. You're a legend
